### ISSUE TITLE
How to go import the 1.8 beta

### ISSUE THREAD

**Issue by guswelter** [neo4j/neo4j-go-driver#103]
Can you help me with how to import the 1.8 beta with go modules? Here is my attempt and error received:

```bash
$ go mod edit -require github.com/neo4j/neo4j-go-driver/neo4j@v1.8.0-beta02
$ go mod tidy
go: github.com/neo4j/neo4j-go-driver/neo4j@v1.8.0-beta02: reading github.com/neo4j/neo4j-go-driver/neo4j/neo4j/go.mod at revision neo4j/v1.8.0-beta02: unknown revision neo4j/v1.8.0-beta02
```

I'm also unable to list available versions:

```bash
$ go list -m -versions github.com/neo4j/neo4j-go-driver/neo4j
go list -m: module github.com/neo4j/neo4j-go-driver/neo4j: no matching versions for query "latest"
```

Any assistance greatly appreciated!

**Comment by 2hdddg** [comment]
Hi @guswelter 
The module name should be github.com/neo4j/neo4j-go-driver (leaving out the neo4j package). 

It could be that it makes sense to have another module on neo4j level as well. Anyway I look into this and make sure that the readme got some info on this.

Thank you for trying it out!
