### ISSUE TITLE
Select database to run neo4j queries

### ISSUE THREAD

**Issue by sahi1422** [neo4j/neo4j-go-driver#105]
I tried queries using pure go beta driver 2(v1.8.0-beta02). I can easily select the database using ':use dbName' in cypher-shell but I don't find a way to select the database of my choice using a neo4j-go driver before running the query. The query result gets reflected in DB with the name "neo4j" by default.

Any help would be greatly appreciated.

**Comment by 2hdddg** [comment]
Hi @sahi1422 
Support for multi databases is an upcoming feature but will not be in the 1.8 version of the driver. There will be a 4.0 driver that matches the server release version and feature set.
Thanks for your feedback!

**Comment by sahi1422** [comment]
Thank you a lot for the information @2hdddg.

We are using neo4j DB and we need a multi DB feature. If the next release will take longer we will be left with no option and maybe we will switch to some other language. Can I please know the tentative date for the release of the 4.0?

It will help us to decide future project plans.

**Comment by 2hdddg** [comment]
@sahi1422 we will try to squeeze multidatabase support into the 1.18 release, seems to be a feature needed by many.

**Comment by 2hdddg** [comment]
Feature included in v1.8.0-beta03
