### ISSUE TITLE
Please add Examples in the docs link at Neo4j official website

### ISSUE THREAD

**Issue by gaurav1999** [neo4j/neo4j-go-driver#110]
Hi,

In the link mentioned at the website which leads to docs for drivers, there is no option/content for Go.
```https://neo4j.com/docs/driver-manual/current``` which is weird, either the link should lead to some page saying "Under Development" or maybe the content should be there.

![Screenshot from 2020-06-05 14-41-32](https://user-images.githubusercontent.com/20752142/83859013-f6df6a00-a73a-11ea-9ae3-42a29566944a.png)
![Screenshot from 2020-06-05 14-41-19](https://user-images.githubusercontent.com/20752142/83859022-f8a92d80-a73a-11ea-80aa-dbec2167cad3.png)

I also wish to know if this is on hold because of 1.8 Release ?

Thanks.

**Comment by mostafa8026** [comment]
Please add example asap.

**Comment by martin-neotech** [comment]
The available examples can be found in https://github.com/neo4j/neo4j-go-driver/blob/1.8/neo4j/test-integration/examples_test.go

For now you have to rely on older drivers manual https://neo4j.com/docs/driver-manual/1.7/client-applications/

The documentation will be improved.
