### ISSUE TITLE
[How to] strcuts from result.

### ISSUE THREAD

**Issue by grizzly-monkey** [neo4j/neo4j-go-driver#115]
- Neo4j version: Community
- Neo4j Mode: Single instance
- Driver version: X lanaguage driver X.Y.Z (If you use some other library that wraps around this driver, you might want to raise an issue there first)
- Operating system: (Ubuntu 16.10 on AWS)

**Neo4j Version:** 4.0.1 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Go driver 1.8.0  
**Operating System:** Ubuntu 16.10 on AWS  

Once running ```session.Run() or Record()```   
how to get the result to the appropriate go lang structs ?

Can we add the feature to the driver ? like mongo does for save , find by Id, filter etcc? 

may be a vanilla ogm ?

**Comment by 2hdddg** [comment]
Hi @grizzly-monkey 
You mean how to map a record to your own struct? You need to retrieve the values from the record and copy each value to your struct members. I'm considering something like https://golang.org/pkg/database/sql/#Row.Scan on the record type to make this a bit easier. In that case you would do this mapping in one call but with many parameters:

err := record.Scan(&s.Member1, &s.otherMember)

OGM functionality like Save and FindById is better implemented on top of the driver, not in the driver. I mean the drivers for Postgres or Sqlite doesn't include ORMs.

**Comment by grizzly-monkey** [comment]
yes ... however mongo driver does give this basic functionality on method save/findById in order to not write the sqls/nosqls. I undestand that mongo does not have sql instead uses function its self vs the cypher is more like SQL.

it returns the value as struct of given type on find.
so was thinking more on how the mongo - go - driver does it instead of Postgres or Sqlite

**Comment by technige** [comment]
Hi @grizzly-monkey - as far as OGM is concerned, this is not functionality we plan to add to the driver itself. However, if we see enough interest, we may build separate OGM libraries that sit atop the driver in future.

**Comment by grizzly-monkey** [comment]
okay ... thanks.
