### ISSUE TITLE
Fail on incorrect NewDriver arguments

### ISSUE THREAD

**Issue by timkofu** [neo4j/neo4j-go-driver#119]
This code runs without printing `err`:

	configForNeo4j40 := func(conf *neo4j.Config) { conf.Encrypted = false }

	driver, err := neo4j.NewDriver("bolt://localGhost:7687", neo4j.BasicAuth("username", "password", ""), configForNeo4j40)
	if err != nil {
		fmt.Println(err)
	}

	defer driver.Close()

Would it be possible to make it fail if any of the arguments to `NewDriver` are wrong?

**Comment by icholy** [comment]
[database/sql.Open](https://golang.org/pkg/database/sql/#Open) also doesn't error when you give it an invalid hostname. They provide a [Ping](https://golang.org/pkg/database/sql/#DB.Ping) method to check the connection.

**Comment by timkofu** [comment]
If possible, all 3 arguments should be checked for validity, and err if any is wrong. A `driver.Ping()` would be great as it would do the same thing.

**Comment by 2hdddg** [comment]
There is a driver.VerifyConnectivity function  on 1.8 branch that hasn't been tagged for release yet. Will be in 1.8.1.
