### ISSUE TITLE
[Question] Clarify requirement to fully consume a Result

### ISSUE THREAD

**Issue by jfancher** [neo4j/neo4j-go-driver#121]
I hit what I thought was a bug, but on further review, I think I was misusing the API. If my (new) understanding is correct, it may be worth clarifying the documentation.

We have a project that executes many concurrent transactions, each of which executes a sequence of a few interleaved reads and writes. I observed the following error in one of the later reads (that is, after the transaction had successfully executed a few queries and updates): `Invalid state 5, expected: [3 0 2]`. This was rare (and I've been unable to create a simple reproducer), but it regularly happened about once per batch of 100k transactions.

Based on [where](https://github.com/neo4j/neo4j-go-driver/blob/1.8/neo4j/internal/bolt/bolt3.go#L387) this error is generated, I suspected the "consume existing stream" logic to be the cause. I realized I was discarding the result of write-only operations (as they are expected to return no data); I added a call to `result.Consume()` after every `Run`. Since then, I haven't observed this failure, although it's hard to say for sure that it's fixed due to its rarity.

Can you confirm that this is the expected usage -- to always fully consume a result, even if it definitely has no records? And that not doing so could result in stream state errors? Or whether there's something to investigate further here?

Thanks!

**Comment by 2hdddg** [comment]
Hi @jfancher 
I agrree that the API part of how to use the Result is a bit confusing. You are right that you should call Consume and in this case you should maybe also add an error check on the error returned by Consume. State 5 indicates that it could be some kind of syntax error in your cypher syntax. This kind of error is not returned by session.Run to be backwards compatible with 1.7 version of the driver but it will be returned when you call Consume. Overhaul of this will be done in upcoming 4.0 driver.

Just to double check, session and result are not thread safe so you should not use these from multiple threads. The driver instance is thread safe so each thread can obtain their own session and result.

**Comment by jfancher** [comment]
I am only using the Session from a single thread, so that's not an issue. I'm also pretty sure I don't have a cypher bug, but it might be a transient error that gets retried in the path where I call `Consume` (but not if I leave it and it later fails with the state error).

In any case, seems like my understanding of the requirement is correct -- I'll keep an eye out for this type of failure, but I think consuming the result fixed it. Thanks for the info!
