### ISSUE TITLE
panic writing data, likely a racing condition problem

### ISSUE THREAD

**Issue by ianhe8x** [neo4j/neo4j-go-driver#123]
**Neo4j Version:** 4.1.1 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Go driver 1.8.0
**Operating System:** Mac OSX

it happens when i wrote a lot nodes into neo4j. It is reproducible btw.
From the screenshot you can see the index is 6 while c.chunks has been reset.
Therefore it led to 
```
panic: runtime error: index out of range [6] with length 0

goroutine 175 [running]:
github.com/neo4j/neo4j-go-driver/neo4j/internal/bolt.(*chunker).Write(0xc00066a690, 0xc0003f5670, 0xe, 0x10, 0x0, 0x0, 0x0)
        /Users/ian/go/pkg/mod/github.com/neo4j/neo4j-go-driver@v1.8.0/neo4j/internal/bolt/chunker.go:64 +0x5ae

```

<img width="493" alt="image" src="https://user-images.githubusercontent.com/39037239/88014785-db59e280-cb73-11ea-954e-21660954fe4e.png">

**Comment by 2hdddg** [comment]
Hi @ianhe8x 
You mention race condition, do you mean that you have multiple threads accessing the same session/transaction/result instance? Those are not thread safe, the driver instance is thread safe and it is assumed that you have separate sessions for each thread.

**Comment by ianhe8x** [comment]
I did mentione racing condition,  it was a wild guess because otherwise i don't know what can explain what happened. Though I did only use one session for all my writes which spread among go routines. I will try one session per worker and let's see if that will work. Thanks.

**Comment by 2hdddg** [comment]
Using one session from multiple go routines will never work, that is the cause of this problem.
