### ISSUE TITLE
session.Run

### ISSUE THREAD

**Issue by gpspelle** [neo4j/neo4j-go-driver#124]
neo4j 4.1.1
go 1.14.6
linux ubuntu 19.04

Hi, I'd like to know if there's any way to run a neo4j cypher command without using an empty map withing the neo4j.session.Run method.

For example, I am doing the following to delete all nodes and relations: 

`result, err := session.Run("MATCH (n) DETACH DELETE n", map[string]interface{}{})`

But, I would like to do something more like:

`result, err := session.Run("MATCH (n) DETACH DELETE n")`

Here's how session is created:

```
configForNeo4j40 := func(conf *neo4j.Config) { conf.Encrypted = false }
driver, err := neo4j.NewDriver("bolt://localhost:7687", neo4j.BasicAuth(user, passwd, ""), configForNeo4j40)
sessionConfig := neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite}
session, err := driver.NewSession(sessionConfig)
```

**Comment by 2hdddg** [comment]
Hi @gpspelle, Go doesn't allow optional parameters but you should be able to pass nil when there are no parameters

**Comment by mt324010** [comment]
what is the usage of the param?

**Comment by fbiville** [comment]
@mt324010 If you have a query like `RETURN $foo, $bar`, you need to pass a map like:
```go
map[string]interface{}{
    "foo": <... some value for $foo ...>,
    "bar": <... some value for $bar ...>
}
```

Does that help?
If you don't have any parameters like in the initial question, you can indeed just pass a `nil` map.
We could revisit this and expose varargs of parameters.
