### ISSUE TITLE
Unable to run multiple queries in one transaction

### ISSUE THREAD

**Issue by aayush2610** [neo4j/neo4j-go-driver#127]
Hi,
I am trying to run a simple multi-query create statement in a transaction, but the node is not getting created. Here is my query

`MATCH (u:User { ID: $UserID }) RETURN (u) <- CREATE (p:Post { ID: $ID })-[r:CREATED_BY {CreatedAt: $Date}]`

This query needs a user with the UserID to be present in the database which I have verified.
I tried to execute this query with `session.Run()`, `session.BeginTransaction()` and `session.WriteTransaction`.

With `session.WriteTransaction`

```	
_, err = session.WriteTransaction(func(transaction neo4j.Transaction) (interface{}, error) {
   result, err := transaction.Run(
	"MATCH (u:User { ID: $UserID }) RETURN (u) <- CREATE (p:Post { ID: $ID })-[r:CREATED_BY {CreatedAt: $Date}]",
	map[string]interface{}{
		"UserID":   post.UserID,
		"ID":       post.ID,
		"Date":     neo4j.LocalDateTimeOf(*post.CreatedAt),
	})
   fmt.Println(err)
   return result.Consume()
})
```

With `session.BeginTransaction`
```
tx, err := session.BeginTransaction()

defer tx.Close()
defer session.Close()

_, err = neo4j.Collect(tx.Run(
           "MATCH (u:User { ID: $UserID }) RETURN (u) <- CREATE (p:Post { ID: $ID })-[r:CREATED_BY {CreatedAt: $Date}]",
	   map[string]interface{}{
		"UserID":   post.UserID,
	        "ID":       post.ID,
		"Date":     neo4j.LocalDateTimeOf(*post.CreatedAt),
           })
)
```

With `session.Run()`
```
_, err = session.Run(
             "MATCH (u:User { ID: $UserID }) RETURN (u) <- CREATE (p:Post { ID: $ID })-[r:CREATED_BY {CreatedAt: $Date}]",
              map[string]interface{}{
		       "UserID":   post.UserID,
	               "ID":       post.ID,
		       "Date":     neo4j.LocalDateTimeOf(*post.CreatedAt),
})
```

With all the three approaches I am not able to create a post node along with a relationship with existing user node.

If a simple query like `CREATE (p:Post { ID: $ID })` is executed in the same session instead of the query mentioned above it is able to create the node.
the session is using the access mode as write
```
session, err := driver.NewSession(neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
if err != nil {
	return err
}
```
Any help would be highly appreciated.

**Comment by 2hdddg** [comment]
Hi @aayush2610 
This isn't really a driver issue, more a cypher syntax question. I guess you want to do something like:
MATCH (u:User {ID: "u1"}) CREATE (u)<-[r:CREATED_BY {x: "y"}]-(p:Post {y: "z"}) RETURN u;

You can join Neo4j open slack channel if you have more questions and want faster feedback: https://neo4j-users.slack.com/

**Comment by aayush2610** [comment]
Thanks for the prompt reply @2hdddg ,
The purpose of my query is to create a new `post` node along with a relationship with existing `user` node. 
I tried the query you posted but it did not work either giving me the error `Invalid handle` - through my service, but this query runs directly on browser
Also, the cypher query I have posted works directly on the browser as expected

PS: I tried joining the neo4j slack group but looks like there is some sign in issue. Will try that back in sometime

**Comment by 2hdddg** [comment]
Hi @aayush2610 I have a look at it and try to run it through the driver. Invalid handle sounds like something the driver could be responsible for. 
Do you have more code surrounding this that I should be aware of.

**Comment by 2hdddg** [comment]
The query I sent you seem to work, the query assumes that you have created a user upfront. The syntax with RETURN (n) <- CREATE .. isn't accepted when I try it in cypher shell.

Cypher shell session:

>CREATE (u:User{ID:'u'}) RETURN u;
+-------------------+
| u                 |
+-------------------+
| (:User {ID: "u"}) |
+-------------------+
>MATCH (u:User{ID:'u'}) CREATE (u)<-[r:CREATED{prop:'x'}]-(p:Post{ID:'p'}) RETURN u, r, p;
+----------------------------------------------------------------+
| u                 | r                      | p                 |
+----------------------------------------------------------------+
| (:User {ID: "u"}) | [:CREATED {prop: "x"}] | (:Post {ID: "p"}) |
+----------------------------------------------------------------+

**Comment by technige** [comment]
Hi @aayush2610 

As @2hdddg points out, you have an illegal Cypher query. `RETURN (u) <- CREATE ...` is not a valid clause and is therefore rightly being rejected by the query engine. If I am guessing correctly what you want to do, you will have to `CREATE` in one clause before `RETURN`ing in another. Your query will then likely be structured as `MATCH ... CREATE ... RETURN`.

The best way to experiment with this will be to use the browser application that comes with the product, available by default at http://localhost:7474.

**Comment by 2hdddg** [comment]
@aayush2610 are you using the same session from multiple go routines? That would explain why you get the error "Invalid handle". Sessions are not thread safe and very light weight, each service request should create it's own session and close it when done.

**Comment by aayush2610** [comment]
@2hdddg No I was not using the same session from multiple goroutines. 
Figured out the issue - I was using the incorrect type of $UserID(passing string whereas the expected type was int) from my program and hence query couldn't find the node with the UserID.
Once I changed the type, the query you suggested as well as the query I posted started working. 
Since I didn't get any type of warning log or error saying that the node does not exist, it took me time to debug the issue. Is there a possibility of emitting either warning log or a specific type of error which makes it easier to debug.

I am new to neo4j so please pardon my naivety.
