### ISSUE TITLE
[Feature Request] : (Enhancement): NeoError 

### ISSUE THREAD

**Issue by grizzly-monkey** [neo4j/neo4j-go-driver#142]
Currently there generic `error` interface that is used to throw error.
As well as the result errors are not part of the error but need to explicitly check record.
`record.Err()`

Instead of this can we have a checked `NeoError` which does proper error mapping with error `code` , `message` etc...
also moving the error from record interface and `Session.Run` itself maps internally to avoid checking the `error`.

**Neo4j Version:** 4.x Community  
**Neo4j Mode**: Single instance  
**Driver version**: Go driver 1.8.2  
**Operating System:** Ubuntu 16.10 on AWS

**Comment by 2hdddg** [comment]
Hi @grizzly-monkey 
I'm not sure exactly what you mean with some of these suggestions.

I cannot see us changing the driver methods to not return the "generic error" interface, I haven't seen any Go package that doesn't use standard error handling. But that is maybe not what you suggest. The 1.8 driver is backwards compatible with 1.7 and shouldn't change much, there is ongoing work on a 4.0 driver with quite a lot of API changes, in this version the database error will be made public so you could check if err is of that type. Please look at 4.0-dev branch for more info..

Not sure what you mean with check record error, there is no record.Err function. Do you mean that you need to check result.Err() before retrieving a record? But that isn't the case, if result.Next returns true, there is a record, you only need to check result.Err when result.Next returns false.

On 1.7, database errors were not returned until starting iterating, so on 1.8 session.Run sometimes "delays" the error to be backwards compatible. On upcoming 4.0 driver this will not be the case. Not sure if this is what you mean with "Session.Run itself maps internally..".

**Comment by grizzly-monkey** [comment]
https://github.com/mongodb/mongo-go-driver/blob/master/mongo/errors.go
Was talking about these kinda error wrapper instead of return `errors.New("some error")`

```
type CommandError struct {
	Code    int32
	Message string
	Labels  []string // Categories to which the error belongs
	Name    string   // A human-readable name corresponding to the error code
	Wrapped error    // The underlying error, if one exists.
}

type WriteConcernError struct {
	Name    string
	Code    int
	Message string
	Details bson.Raw
}
etc...
```


for record.Err()

```
res, neoErr := dao.client.Session().Run(dao.cypher.TreeQuery(), map[string]interface{}{
		"NUMBER": partNumber,
		"REVISION":    revision,
	})

	if neoErr != nil { 
		return nil, mappers.MapNeoErr(neoErr)
	}

	if res.Err() != nil {  //// i need to check here for result error as well instead of this if we can get this mapped in neoErr so can save 2 checks.
		return nil, mappers.MapNeoErr(neoErr)
	}
```

**Comment by 2hdddg** [comment]
Ok, I guess you mean result.Err() at all places where record.Err() is mentioned.

You don't need to check the error two times as you do in your example, what you see there is an effect of backwards compatibility where error that used to happen during iteration now happens on Run (therefore delayed). You should write your code as
res, err := session.Run(...)
if err != nil {
   return err
}
// Loop through the result
while res.Next() {
    // do stuff with records...
}
// Handle error that happened during iteration
if err = res.Err(); err != nil {
   return err
}

Internally there is a bunch of typed errors like in your example, they are not exposed through the API on 1.x branch, some will be on 4.0, at least DatabaseError in: https://github.com/neo4j/neo4j-go-driver/blob/4.0-dev/neo4j/db/errors.go

What is the reason you want the underlying error structs? They are used internally to control retry logic and other things. But if we are exposing them they are part of the API.

**Comment by grizzly-monkey** [comment]
> What is the reason you want the underlying error structs? They are used internally to control retry logic and other things. But if we are exposing them they are part of the API.


It helps in mapping the errors or categorizing them. What I am doing is depending upon the DB error code i map it to  appropriate HTTP status code eg. 400 , 503 etc...

**Comment by 2hdddg** [comment]
Access to the database error is already in the plan for upcoming 4.0 release of the driver. Not sure what we do for 1.8. 
I doubt that the database errors will be very helpful for generating HTTP status codes. You need to check the Neo4j manual for types of errors, these are the kinds of errors you get when you can connect to a database instance, other types of errors will not be database errors.

**Comment by grizzly-monkey** [comment]
okay i will wait for 4.0 release.. any ETA for this ?
