### ISSUE TITLE
record value type *neo4j.node.  unable to work with it.

### ISSUE THREAD

**Issue by azamaulanaaa** [neo4j/neo4j-go-driver#165]
Operation System : Win 10
Go Version : 1.15.2
Neo4j Version : 4.1.3 Comunity
Driver Version : Go Driver 1.8.3

Steps to reproduce (short version)
1. read transaction with query
`Match (n) return n`
2. if record value type `*neo4j.Node` do something else `panic`
3. Got panic
```
panic: (*neo4j.node) 0xc0000ca3d0
```

Expected
value type should be ` *neo4j.Node`.

 `*neo4j.node` was not exported. unable to work with it.

**Comment by 2hdddg** [comment]
@azamaulanaaa you should use neo4j.Node not *neo4j.Node.
neo4j.Node is an interface, implemented by the non exported type *neo4j.node.
I guess you have something like:
n := record.Values(0).(*neo4j.Node) where it should be
n := record.Values(0).(neo4j.Node)
