### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by desdic** [neo4j/neo4j-go-driver#19]
Hi,

It seems that the timeout in session.Run is not fully implemented. Is there a way to cancel a session or transaction in order to do a timeout ? If I run a close on transaction or session in a different go routine the runner panics

**Comment by ali-ince** [comment]
Hi @desdic,

The API for transaction timeout and metadata was introduced with [v1.7.0-beta01](https://github.com/neo4j/neo4j-go-driver/wiki/1.7-changelog#v170-beta01), but actual implementation for it arrived with [v1.7.0-beta02](https://github.com/neo4j/neo4j-go-driver/wiki/1.7-changelog#v170-beta02).

Bolt V3, which is the enabler for transaction timeout and metadata feature, will be part of neo4j 3.5 (you can try out the latest pre-release [3.5.0-beta01](https://neo4j.com/release-notes/neo4j-3-5-0-beta01)). If you're trying to implement this on previous server versions, it's not possible to cancel a transaction from the driver, but you can set a global [transaction timeout](https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.transaction.timeout) on the server.

Thanks.

Ali

**Comment by zhenlineo** [comment]
@desdic 
Thanks again for reporting this issue. The request feature is already included in the drivers and will work with the current 3.5 server. Pls let us know if there is other issues.
