### ISSUE TITLE
Transaction query: iterating through embedded table of maps

### ISSUE THREAD

**Issue by makubit** [neo4j/neo4j-go-driver#201]
I have a specific case of query, where I'm passing embedded table of maps, that stores information about multiple relations from one node. Query that I formed is presented below:

```
records, err := transaction.Run(
			`MATCH (i:Instnace {id: $id})
			MATCH (p:Policy {policy: $policy[0]["iso"]})
			CREATE (i)-[:HAS {accessPolicy: $policy[0]["accessPolicy"]}]->(p)
			RETURN i.id AS id`,
			map,
		)
```

I wonder if there is any possibility to iterate through the `policy` table. I'm able to get parameters from the embedded map, but I couldn't find anything that would support iterating through the table (only directly passing index).

 Is it supported or is there any other solution for my case?

**Comment by makubit** [comment]
The second thing I tried is passing an additional parameter (int) where I store information about iteration. In this case I'm getting error:
```
"Server error: [Neo.ClientError.Statement.TypeError] Cannot index a list using an non-integer number, got Double(0.000000e+00)"
```
I think it's a  bug, in my struct I specified this parameter as int and it's not casting it correctly.

**Comment by fbiville** [comment]
What about something like:
```cypher 
MATCH (i:Instance {id: $id})
UNWIND $policy AS policy 
MATCH (p:Policy {policy: policy["iso"]})
CREATE (i)-[:HAS {accessPolicy: policy["accessPolicy"]}]->(p)
RETURN i.id AS id
```

Note: this question seems better suited to https://community.neo4j.com/c/drivers-stacks/go/34 than GitHub, as we tend to use GitHub issues about driver bugs, more than about driver usage.

**Comment by fbiville** [comment]
Closing now, feel free to reopen @makubit if my suggestion did not help!
