### ISSUE TITLE
Mysterious Compile time issues re: Minimum Viable Snippet

### ISSUE THREAD

**Issue by mantis-sa** [neo4j/neo4j-go-driver#240]
Hi Neo4J Team,

Not sure whether the following is a bug in the code, or something is wrong with my setup. I thought I would report here and try to solve it in parallel in case anyone spots something I am missing.

The code example is lifted exactly as is (bar the username and password change) from the Minimum Viable Snippet section of https://github.com/neo4j/neo4j-go-driver/tree/v4.3.0

**Neo4j Version:** 4.3.0 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Go driver v4.3.0
**Golang version**: Go SDK 1.13.5  
**Operating System:** Windows 10 Pro

How I initialised this demo project: 
![1_Project_Startup](https://user-images.githubusercontent.com/11036157/122791888-8d80b980-d2b1-11eb-851a-a54acbcc33aa.PNG)

Total Number of files in project + their location:
![2__Project_Files_Location](https://user-images.githubusercontent.com/11036157/122792013-aab58800-d2b1-11eb-82d1-3443c9ffc87b.PNG)

GOPATH on my machine:
![3__GoPath](https://user-images.githubusercontent.com/11036157/122792080-bacd6780-d2b1-11eb-9759-bde248601d74.PNG)

Neo4J Driver Version used (note how it's the same path as my GOPATH, so I assume this is the one it's using):
![4__Neo4j_version](https://user-images.githubusercontent.com/11036157/122792210-dafd2680-d2b1-11eb-931c-f86ae4e46e96.PNG)

### Steps to reproduce
1. Download the code : https://github.com/d1no93/neo4j_demo
2. Load up the project into GoLand / IntelliJ
3.  Create a run config of the following:

- Package path: neo4j_demo
- Working directory: PATH_TO_NEO4J_DEMO
- Module: neo4j_demo

4. Run the program
### Expected behavior
Program expected to compile and run given the following is true:

- **NewSession** returns a **Session** (See https://github.com/neo4j/neo4j-go-driver/blob/4.3/neo4j/driver.go)
- **Result** has a method on the interface called **Single** (See https://github.com/neo4j/neo4j-go-driver/blob/4.3/neo4j/result.go)

Please see the following 2 images as proof that the file versions in my GOPATH are correct.
![NewSession_Single_Return](https://user-images.githubusercontent.com/11036157/122793724-70e58100-d2b3-11eb-9f74-b05386609fb3.PNG)
![Single_Exists](https://user-images.githubusercontent.com/11036157/122793725-717e1780-d2b3-11eb-9838-3aa8b1d56a50.PNG)

### Actual behavior
5. See the message in [
![5_Compile_Message](https://user-images.githubusercontent.com/11036157/122791593-45fa2d80-d2b1-11eb-8bda-1baa867aad49.PNG)
](url)

Like I said above, not sure whether something has gone awry in my setup, or whether this is legitimately a bug in the driver. Either way, if someone could replicate the setup I have on their machine and report back whether they face the same issue / notice something wrong in my setup, that would be super helpful.

**Comment by fbiville** [comment]
Hello @d1no93, the problem is that the import for the driver was wrong: `"github.com/neo4j/neo4j-go-driver/neo4j"` instead of the documented `"github.com/neo4j/neo4j-go-driver/v4/neo4j"`.
I sent a PR to your project to fix it: https://github.com/d1no93/neo4j_demo/pull/1/.
