### ISSUE TITLE
Neo.ClientError.Statement.SemanticError is not thrown to app

### ISSUE THREAD

**Issue by Kubera2017** [neo4j/neo4j-go-driver#272]
I have in logs  DEBUG  [bolt4 bolt-204@localhost:7687] Neo4jError: Neo.ClientError.Statement.SemanticError (Cannot merge the following node because of null property value for 'id': (:Node_label {id: null})),  But it does not throw an error in session.Run() or tx.Run()

**Comment by 2hdddg** [comment]
The driver will not report all kinds of errors on the Run method, client code needs to handle errors while iterating as well. So check the error after iterating through the records. That is check what Result.Err() returns after iteration or the error returned from Collect/Single/Consume methods.

**Comment by Kubera2017** [comment]
Hello. Thanks for response, I think it is better to have it documented, I tested with JS driver, it throws that error directly in .run(), and also Python driver, it throws only in consumption (as in Go)

**Comment by fbiville** [comment]
@Kubera2017 did you have a specific documentation resource in mind? I'm happy to update it to include some error handling examples.

**Comment by Kubera2017** [comment]
I think just need to add it to README

**Comment by fbiville** [comment]
@Kubera2017 WDYT of https://github.com/neo4j/neo4j-go-driver/pull/291?
