### ISSUE TITLE
neo4j-go-driver stuck when send a big cypher query(>2k)  in cross idc environment

### ISSUE THREAD

**Issue by garycaokai** [neo4j/neo4j-go-driver#275]
neo4j-go-driver stuck when send a big query(2k) when we use neo4j-go-driver in cross idc environment,  after some research，we found that 0xffff is too big for  cross idc environment, when we changed this value, it works.
so we recommend to add an option in create new driver to set  the max chunker size parameter

> https://archive.nanog.org/sites/default/files/wednesday_general_steenbergen_antijumbo.pdf 
> What the heck is a Jumbo Frame?
> • Technically, the IEEE 802.3 Ethernet standard defines
> the maximum frame payload (MTU) value at 1500 bytes.
> • Supporting anything larger than 1500 bytes is outside of
> this standard, and we call it a “Jumbo Frame”

my little fix
https://github.com/garycaokai/neo4j-go-driver
+++neo4j/internal/bolt/chunker.go 
```
@@ -59,21 +59,22 @@
 	// Try to make as few writes as possible to reduce network overhead
 	// Whenever we encounter a message that is bigger than max chunk size we need
 	// to write and make a new chunk
+	// max chunk size should not bigger than mtu(ie, 1500)
 	start := 0
 	end := 0
 
 	for _, size := range c.sizes {
-		if size <= 0xffff {
+		if size <= 0x04b0 {
 			binary.BigEndian.PutUint16(c.buf[end:], uint16(size))
 			// Size + messge + end of message marker
 			end += 2 + size + 2
 		} else {
 			// Could be a message that ranges over multiple chunks
-			for size > 0xffff {
-				c.buf[end] = 0xff
-				c.buf[end+1] = 0xff
+			for size > 0x04b0 {
+				c.buf[end] = 0x04
+				c.buf[end+1] = 0xb0
 				// Size + messge
-				end += 2 + 0xffff
+				end += 2 + 0x04b0
 
 				_, err := wr.Write(c.buf[start:end])
 				if err != nil {
@@ -83,7 +84,7 @@
 				// of the chunk
 				end -= 2
 				start = end
-				size -= 0xffff
+				size -= 0x04b0
 			}
 			binary.BigEndian.PutUint16(c.buf[end:], uint16(size))
 			// Size + messge + end of message marker

```

**Comment by fbiville** [comment]
Hi @garycaokai, I'm back from parental leave. 
Would you mind explaining to me what "cross IDC" means, I'm not familiar with the term 😃 

Also, would you mind sharing a query example and some setup details to help me reproduce the issue? That would help tremendously.

**Comment by fbiville** [comment]
The change you suggest is a specification change (see https://7687.org/bolt/bolt-protocol-message-specification-4.html#chunking) and will require all drivers to comply to it.

I would need more information about the environment you are referring to, else I will not necessarily be able to efficiently advocate for this change.

**Comment by garycaokai** [comment]
@fbiville thank you for your reply.
"cross IDC"  means that we have several Neo4j Golang clients locating in A idc to access the Neo4j Server locating in B idc. 
It is  VXLAN network, the problem is that VXLAN packets cannot be fragmented. 
When we send a big query(packet)(> 2K), it get stuck. that is why I hack some source code to fix it for my specific network problem.

**Comment by fbiville** [comment]
Hi @garycaokai, after consideration by the team, we have decided not to go forward with this request for the moment.
If that changes, we will let you know.
