### ISSUE TITLE
AccessModeWrite not connecting to the leader member

### ISSUE THREAD

**Issue by headyj** [neo4j/neo4j-go-driver#276]
With a causal neo4j instance (4.1.5) on a kubernetes cluster (created using Helm), I connect using the AccessModeWrite:
```
c, err := neo4j.NewDriver(c.Host, neo4j.BasicAuth(c.Username, c.Password, ""))
session := c.NewSession(neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
defer session.Close()

_, err = session.Run("CREATE DATABASE myDatabase", map[string]interface{}{})
if err != nil {
return diag.FromErr(err)
}
```

But still having the the following error message:
```
Neo.ClientError.Cluster.NotALeader (Failed to create the specified database 'myDatabase': Administration commands must be executed on the LEADER server.)
```

I tried with both neo4j and bolt schemes, still the same issue:
`bolt://<neo4j-namespace>.<neo4j-name>.svc.cluster.local:7687`
`neo4j://<neo4j-namespace>.<neo4j-name>.svc.cluster.local:7687`

EDIT: same issue if I specify system database:
```
session := c.NewSession(neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite, DatabaseName: "system"})
```

**Comment by fbiville** [comment]
I'm now back from parental leave, I'll do my best to have a look at this this week. Thanks for the report.

**Comment by fbiville** [comment]
So, a few things to note before going further:

- you should handle the driver creation error before proceeding to the session creation and close the driver at some point (but this might in a later part of your program already)
- `neo4j` is definitely the scheme to use, as it will make the driver routing-aware
- the system database should definitely be specified

My setup is not exactly apples-to-apples compared to yours, but I just ran the [following causal cluster locally with Docker Compose](https://neo4j.com/docs/operations-manual/current/docker/clustering/#docker-cc-setup-dockercompose) (replacing 4.3 with 4.1.5).

I then ran the following program:

```go
package main

import (
	"fmt"
	"github.com/neo4j/neo4j-go-driver/v4/neo4j"
)

func main()  {
	c, err := neo4j.NewDriver("neo4j://localhost", neo4j.BasicAuth("neo4j", "foobar", ""))
	if err != nil {
		panic(err)
	}
	defer c.Close()
	session := c.NewSession(neo4j.SessionConfig{
		AccessMode: neo4j.AccessModeWrite,
		DatabaseName: "system",
	})
	defer session.Close()

	res, err := session.Run("CREATE DATABASE myDatabase", map[string]interface{}{})
	if err != nil {
		panic(err)
	}
	summary, err := res.Consume()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", summary)
}
```

If you try the same program as above (after changing the credentials), do you still encounter an error?

**Comment by fbiville** [comment]
@headyj have you been able to reproduce the issue with the code I provided above?

**Comment by fbiville** [comment]
Feel free to reopen this @headyj if you still need help.
