### ISSUE TITLE
bolt/bolt.h not found

### ISSUE THREAD

**Issue by vikashvverma** [neo4j/neo4j-go-driver#34]
I am using latest release and trying to build the app with static linking but I get following error while building:
```
../../../github.com/neo4j-drivers/gobolt/connection.go:25:10: fatal error: 'bolt/bolt.h' file not found
#include "bolt/bolt.h"
         ^~~~~~~~~~~~~
1 error generated.
```

Any help would be appreciated.

**Comment by MtthwBrwng** [comment]
Are you up to date on seabolt? If not, I'd try downloading the release of seabolt that goes with the version of the driver you're using or building seabolt from source then try to build you app again.

If that doesn't help, then try go getting the latest version of gobolt.

**Comment by jmaeso** [comment]
Same happens here:

I had neo4j-go-driver working a couple of months ago.
Today tried to execute and had an error for seabolt. I pulled latest code, built from source, but the PKG_CONFIG_PATH could not find `seabolt17.pc` compiling seabolt creates `seabolt.pc` .  I just created a copy of the same file but renaming it.
Now I get the exactly same error but with modules error:
```
../../../../pkg/mod/github.com/neo4j-drivers/gobolt@v1.7.0/connection.go:25:10: fatal error: 'bolt/bolt.h' file not found
```

**Comment by vikashvverma** [comment]
@MattJBrowning @jmaeso The issue is resolved for me.

I had set `PKG_CONFIG_PATH` to `seabolt/build/share/pkgconfig` instead of `seabolt/build/dist/share/pkgconfig`. I have also set `DYLD_LIBRARY_PATH` but not required for static linking.

The README does not specify exact path to choose as the path seems to redundant.

@jmaeso let me know if that works for you?

**Comment by jmaeso** [comment]
Thank you @vikashvverma for your quick answer.
When I compile seabolt I don't get `dist/` I just have `bin/` `lib/` and `seabolt.pc`. I compiled it as a release, not debug. Could be because of that?

**Comment by vikashvverma** [comment]
@jmaeso I had compiled as debug and not as release. You could try this...

**Comment by jmaeso** [comment]
Didn't work. I ended up using the released package. Both on local and on the CI
Setup for the CI:
```
dist: xenial

before_install:
  - wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.0/seabolt-1.7.0-Linux-Ubuntu-Xenial.deb
  - sudo dpkg -i seabolt-1.7.0-Linux-Ubuntu-Xenial.deb
  - export PKG_CONFIG_PATH="/usr/local/share/pkgconfig"
```

**Comment by ali-ince** [comment]
@jmaeso I think you cmake cache is out of date, could you please try removing `build` directory and run `make_debug.sh`? That should result in `build/dist` be created and also those `.pc` files should have `17` in their names.

**Comment by jmaeso** [comment]
In fact I get: `Error: could not load cache` at the end of the make

**Comment by ali-ince** [comment]
I don't know what did go wrong in your environment, but it seems something is wrong. I could only suggest a `git clean -ixd`  confirming to clean-up everything and start from scratch.

**Comment by collisonchris** [comment]
I've been able to get this working on OS X workstations and built on a CI server targeting Alpine based images. Making sure all the paths were set on the CI server was a pain but it's do able. 
As part of our CI build, after cloning and building from source in `/seabolt`, I set the following vars as part of my setup:
```
      - export PKG_CONFIG_PATH=/seabolt/build/dist/share/pkgconfig
      - export LD_LIBRARY_PATH=/seabolt/build/dist/lib64
      - export C_INCLUDE_PATH=/seabolt/build/dist/include
```

**Comment by ali-ince** [comment]
You may want to have a look at [our latest blog post](https://medium.com/neo4j/neo4j-go-driver-is-out-fbb4ba5b3a30) that shows how to build a static linked go binary with docker - and also our latest [PR #56](https://github.com/neo4j-drivers/seabolt/pull/56) that includes build / package docker files.

@jmaeso could you please confirm that the suggested solutions work for you?

**Comment by jmaeso** [comment]
I didn't do the entire process (because I used the already compiled binaries and are spread through `/usr/var/local`), but could compile with the good result doing the git cleanup. Thank you @ali-ince.
