### ISSUE TITLE
Unable to cross compile

### ISSUE THREAD

**Issue by vikashvverma** [neo4j/neo4j-go-driver#37]
I am trying to Cross compile binary for different OS/Arch (`env GOOS=linux GOARCH=amd64 go build -o build/foobar --tags "seabolt_static" foo/bar/main.go`) but I am getting following errors.

```
vendor/github.com/neo4j-drivers/gobolt/config.go:40:86: undefined: ConnectorError
vendor/github.com/neo4j-drivers/gobolt/config.go:41:68: undefined: DatabaseError
vendor/github.com/neo4j-drivers/gobolt/config.go:42:66: undefined: GenericError
vendor/github.com/neo4j-drivers/gobolt/config.go:43:25: undefined: Logging
vendor/github.com/neo4j-drivers/gobolt/config.go:44:25: undefined: URLAddressResolver
```

The compilation works fine if we just compile for current OS(`go build -o build/foobar --tags "seabolt_static" foo/bar/main.go`).

Any help would be appreciated.

P.S. Creating issue here because `github.com/neo4j-drivers/gobolt` does not allow to create issue.

**Comment by vikashvverma** [comment]
@ali-ince @technige Any help with this would be appreciated.

**Comment by ali-ince** [comment]
Hi @vikashvverma,

We don't have any CI set up for verifying cross-compilation scenarios and I believe `CGO` makes the huge cross-compilation experience a bit harder out there.

We'll try to come up with a solution eventually, but for the time being I would suggest using docker to create a binary built for linux. A sample docker file is available in our latest blog post [here](https://medium.com/neo4j/neo4j-go-driver-is-out-fbb4ba5b3a30).

I'll update this issue when we have a working cross-compilation instructions.

Thanks.

Ali

**Comment by vikashvverma** [comment]
I believe using Docker container would fix the compilation for Linux but we want binaries for the different OS to be generated. We tried manually cross compiling on Mac OS but it didn't work as you can see the error message. Our ultimate goal is to generate binaries for different OS/Arch from CI server and store the artifacts. 

I would let you know if cross compiling works on Linux.

**Comment by vikashvverma** [comment]
Cross-compiling is not working on Linux as well, the same error above.

**Comment by ali-ince** [comment]
Hi @vikashvverma,

Thanks for reporting this issue, but as I mentioned earlier in the thread, we depend on `CGO` to make use of seabolt native library (and it depends on openssl as well). We have discussed internally to come up with a procedure (possibly based on https://github.com/karalabe/xgo) - but it's not trivial even to add `cmake` build support onto that and we currently don't have the capacity to implement it.

I'm closing this issue with won't fix.

Thanks.
