### ISSUE TITLE
[Feature Request + Bug] Option to disable cypher query validation

### ISSUE THREAD

**Issue by joshua-auchincloss** [neo4j/neo4j-go-driver#400]
Current driver settings disallow arbitrary cypher statements (even though they are valid). Eg ":begin" will throw an error, this should instead be disabled in driver or tx settings to allow the users decision whether to validate the query.

**Comment by fbiville** [comment]
Hello, thanks for raising the issue.
For reference, `:begin` is not part of the Cypher language but rather a Cypher-Shell command.
