### ISSUE TITLE
Get data in graph format directly

### ISSUE THREAD

**Issue by gschurck** [neo4j/neo4j-go-driver#402]
Is it possible to get the result of a cypher query in graph format directly, [like in the HTTP API](https://neo4j.com/docs/http-api/current/actions/return-results-in-graph-format/) ?
For example to return the graph directly from the backend to display a graph visualization on the frontend.

**Comment by fbiville** [comment]
Hello, there is no built-in support for this.
If you need help implementing this, I'm happy to continue the conversation on Discord: https://neo4j.com/developer/discord/.
Once you get a `Result` or `ResultWithContext`, you'll need to call, in order:

- `Keys`
- loop of (`Next`+`Record` or `NextRecord`) or just `Collect`
- if you're calling `Record` or `NextRecord`, call and act upon the result of `Err` at the end of the iteration
- `Consume`

**Comment by gschurck** [comment]
Okay thank you.

**Comment by gschurck** [comment]
Could it be an interesting feature to add in a PR for this driver ? I think it would be useful to have it as build-in.
For example in the Python driver there is [graph](https://neo4j.com/docs/api/python-driver/current/api.html#graph) and [data](https://neo4j.com/docs/api/python-driver/current/api.html#neo4j.Result.data) functions to get a more ordered format directly.

**Comment by gschurck** [comment]
Finally, I found that it's possible to export the graph data as JSON with cypher query directly
```
CALL apoc.export.json.all(null,{useTypes:true, stream: true, jsonFormat: "JSON"})
YIELD data
RETURN data
```
So it seems that it's the optimal way for an API to get neo4j graph data as JSON and return it directly in response.
