### ISSUE TITLE
Slice of struct as query params for cypher

### ISSUE THREAD

**Issue by vikashvverma** [neo4j/neo4j-go-driver#41]
I am trying to execute a cypher query with params as slice of struct. 
I see the slice of struct not getting parsed correctly, as a result the query is not behaving as expected.

Please find below more details:

**Sample Query**
```
WITH {Nodes} as nodes
UNWIND nodes as node
...
...
```

**Scenario1**

Struct:
```
type Node struct {
	ID int64   `json:"id"`
	X  float64 `json:"x"`
	Y  float64 `json:"y"`
}
```

The parameter being passed is a slice of Node, `[]Node{}`.
When i enabled debug mode for the driver, I am getting following:
`{Nodes: [null, null, null, null]}`

**Issue**: Slice of struct not getting parsed

**Scenario2**

Struct:
```
type Node struct {
	ID interface{}   `json:"id"`
	X  interface{} `json:"x"`
	Y  interface{} `json:"y"`
}
```
**Issue**: Slice of struct not getting parsed

The parameter being passed is a slice of Node, `[]Node{}`.
When i enabled debug mode for the driver, I am getting following:
`{Nodes: [null, null, null, null]}`

**Scenario3**

Struct:

```
type Node interface{}
```
The parameter being passed is a slice of Node, `[]Node{}`.
When i enabled debug mode for the driver, I am getting following:

```
{Nodes: [{id: 1.429700E+04, x: -7.545518E+00, y: -1.147595E+01}, {id: 1.431900E+04, x: 1.613901E+01, y: -1.043397E+01}, {id: 1.430600E+04, x: 7.367213E+00, y: 1.157960E+01}, {y: 1.033033E+01, id: 1.429300E+04, x: -1.596071E+01}]}
```

**Issue** `id` value is getting converted to float even if it is integer.

I am unmarshalling the request payload directly into `Node` struct and the request payload is always sending `id` as `int`, `x` as `float` and `y` as `float`.

A sample request is as follows: 

```
[{"id":14297,"x":-7.545517921447754,"y":-11.475950241088867},{"id":14319,"x":16.139013290405273,"y":-10.43397331237793},{"id":14306,"x":7.367213249206543,"y":11.579595565795898},{"id":14293,"x":-15.960708618164062,"y":10.330327987670898}]

```

Could you help me resolve this?

**Comment by ali-ince** [comment]
Hi @vikashvverma,

Sending user defined types as query parameters is not supported. The supported types are listed at https://github.com/neo4j/neo4j-go-driver#value-types, https://github.com/neo4j/neo4j-go-driver#spatial-types---point and https://github.com/neo4j/neo4j-go-driver#temporal-types---date-and-time. Of those types listed, you cannot send `neo4j.Node`, `neo4j.Relationship` and `neo4j.Path` values as query parameters.

You can however convert your struct values into `map[string]interface{}` instances and send them as such.

I'm closing the issue, please feel free to re-open if the suggestion above doesn't work for you.

Thanks.

**Comment by vikashvverma** [comment]
Right,
I used `[]map[string]interface{}` and it worked.

Thanks
