### ISSUE TITLE
Instructions for starting a Docker container in order to run integration tests do not work

### ISSUE THREAD

**Issue by asarkar** [neo4j/neo4j-go-driver#427]
Instructions for starting a Docker container in order to run integration tests do not work.
https://github.com/neo4j/neo4j-go-driver#integration-and-benchmark-testing

**Neo4j Version:** 5.3.0 Community  
**Neo4j Mode**: Docker
**Driver version**: Go driver at commit 8a53610e
**Operating System:** macOS

### Steps to reproduce
1. Create Neo4j Docker container using the following command
```
docker run \   
  --rm \
  --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
  --env NEO4J_AUTH=neo4j/pass \
  -p7474:7474 -p7687:7687 \
  neo4j:latest
```

### Expected behavior
The container starts successfully
### Actual behavior
The container fails to start unless `--env NEO4J_dbms_security_auth__minimum__password__length=4` is set.
```
Invalid value for password. The minimum password length is 8 characters.
If Neo4j fails to start, you can:
1) Use a stronger password.
2) Set configuration dbms.security.auth_minimum_password_length to override the minimum password length requirement.
3) Set environment variable NEO4J_dbms_security_auth__minimum__password__length to override the minimum password length requirement.
java.lang.IllegalArgumentException: A password must be at least 8 characters.
	at org.neo4j.commandline.admin.security.SetInitialPasswordCommand.validatePassword(SetInitialPasswordCommand.java:114)
	at org.neo4j.commandline.admin.security.SetInitialPasswordCommand.execute(SetInitialPasswordCommand.java:71)
```

**Comment by fbiville** [comment]
Thanks, good catch. This is due to a change in the minimal length of password starting with Neo4j 5.3. Let me update the docs.
