### ISSUE TITLE
[Feature Request] Deduce Neo4J version in integration tests

### ISSUE THREAD

**Issue by asarkar** [neo4j/neo4j-go-driver#428]
Currently, running the integration tests require setting environment variables like `TEST_NEO4J_HOST="localhost" TEST_NEO4J_VERSION=4.4`. I recommend making these optional; the host can be assumed to be localhost, and the version can be deduced as follows.
```
call dbms.components() yield name, versions, edition unwind versions as version return name, version, edition;

name        | version   | edition
------------|-----------|-----------
Neo4j Kernel¦  3.5.6    ¦enterprise
```

**Comment by fbiville** [comment]
Hello @asarkar, thanks for this.
It's a good idea and it's actually been on my TODO list for quite a while but never got to do it.
Would you be interested in creating a pull request for this?

**Comment by asarkar** [comment]
I'd like to but I'm not sure if I can find time anytime soon. I guess we can leave this ticket open until someone finds time to do it. That someone could be me, you, or perhaps another user.

**Comment by lucapirolo** [comment]
Hi,

I've implemented the feature request as per the discussion in the issue. Please find the Pull Request here for the dynamic version and host configuration enhancement: [PR #544](https://github.com/neo4j/neo4j-go-driver/pull/544).

Looking forward to your feedback.

Thanks Luca

**Comment by StephenCathcart** [comment]
Closing due to #544 being merged. Thank you again @lucapirolo for your contribution!
