### ISSUE TITLE
Errors in Go's Driver Manual

### ISSUE THREAD

**Issue by mariecurried** [neo4j/neo4j-go-driver#43]
I'm new to Neo4j and I've been playing around with the whole platform. Lately, I've been experimenting with interacting with the DB from a Go program.
While reading the Driver Manual, I found a couple of errors in the examples.
In the section "3.3. Causal chaining", the function makeFriend is not using the bookmarks argument, which leads to an incorrect example.
In the section " 4.1. The Cypher type system", the equivalent to Neo4j's null type in Go is nil, not null.
In section "4.2.3. Consuming the stream", in the example a Session is created with AccessModeWrite, but the transaction run only reads. In spite of not making a difference in practice, I think it should be changed to AccessModeRead for consistency.

Thanks in advance,
Maria

**Comment by ali-ince** [comment]
Hi @marigonzes,

Thank you for reporting the inconsistencies you've discovered.

We've fixed the problems you've pointed and they will be published just after the release of the next patch version, 1.7.2.

Thanks.

**Comment by mariecurried** [comment]
Thank you :smile:

**Comment by mariecurried** [comment]
Don't know if this is the best place to ask a question, but here it goes:
- Is it necessary to consume a result from a Session or a Transaction if I don't need it's contents, for example, when executing a CREATE request? I ask this, because sometimes, if I don't consume the result, the values are not written to the server.

**Comment by ali-ince** [comment]
It would definitely be better to direct your questions to our community site, available at https://community.neo4j.com.

The behaviour you’re experiencing is related with a bug, resolved with #42 and will be available with 1.7.2 release. In the meantime, it is best to explicitly call `result.Consume()` as you’ve already discovered.
