### ISSUE TITLE
Why can't I connect to the local neo4j server?

### ISSUE THREAD

**Issue by FLAGLEE** [neo4j/neo4j-go-driver#447]
neo4j version: 5.4.0 Community
neo4j-go-driver version: v5.5.0

When I run the https://github.com/neo4j/neo4j-go-driver#minimum-viable-snippet
I got
```
panic: TransactionExecutionLimit: Timeout after 5 attempts, last error: server responded with unsupported version 80.84
```
Why can't I connect to the local neo4j server?

**Comment by FLAGLEE** [comment]
I solved this problem, just found out that there is a web server that is still connected to this database.

**Comment by fbiville** [comment]
Ah indeed, the infamous 80.84 version happens when the Go driver talks to a HTTP server.
The driver tries to parse the handshake and fails :)
We have an internal issue filed about this to make the error a little more explicit.
