### ISSUE TITLE
`Driver` type does not show as Deprecated in API docs

### ISSUE THREAD

**Issue by stefano-ottolenghi** [neo4j/neo4j-go-driver#502]
`NewDriver` shows as deprecated, while `Driver` does not. 

![Screenshot from 2023-06-13 04-07-37](https://github.com/neo4j/neo4j-go-driver/assets/114478074/6c5e7303-a043-40c6-abf2-55bafa20b5f0)

**Comment by fbiville** [comment]
Thanks, let me fix that.

**Comment by fbiville** [comment]
Hmmm, that is strange, the deprecated comment is there: https://github.com/neo4j/neo4j-go-driver/blob/0341d94da97a3f3ce2744c26e90c90a095c75ce3/neo4j/driver.go#L30.
Same as `NewDriver`: https://github.com/neo4j/neo4j-go-driver/blob/0341d94da97a3f3ce2744c26e90c90a095c75ce3/neo4j/driver.go#L64 🤔

**Comment by fbiville** [comment]
Well, well... `Deprecated: ` is supposed to be the start of a **new**  paragraph, which requires a blank line beforehand.
And it was missing 🤦 
Running the same tool as pkg.go.dev (`go install golang.org/x/pkgsite/cmd/pkgsite@latest && pkgsite`) allowed me to confirm the issue.

**Comment by fbiville** [comment]
Turns out there were a few other occurrences of this problem 😓
