### ISSUE TITLE
Data in query response map is a *neo4j.nodeValue, a private type. Can't get at the get at data.

### ISSUE THREAD

**Issue by bmschwartz** [neo4j/neo4j-go-driver#51]
One of the match queries I run returns a data map with one property being an empty interface of type `*neo4j.nodeValue`, making it impossible to access the data. I can use reflection to get a `neo4j.nodeValue` object but attempting to coerce the type to neo4j.Node fails.

**Neo4j Version:** 3.3.6 Enterprise  
**Neo4j Mode**: Casual cluster with 1 core 2 read-replica  
**Driver version**: Go driver 1.7.2
**Operating System:** macOS 10.14.3

### Steps to reproduce
1. Begin a new Transaction `session.BeginTransaction()`
2. Run a query: `if resp, err := tx.Run(query, map[string]interface{}{}); err != nil { ... }`
3. Get the first record: `record := resp.Record().GetByIndex(0).(map[string]interface{})`
4. Access data on the record: `answer, err := record["answer"]`

### Expected behavior
Ideally, `answer` should be an `interface{}` that can immediately be cast to a `neo4j.Node` type.

### Actual behavior
Instead, `answer` is an empty interface of type `*neo4j.nodeValue`, which is a private type. I can use reflection to make this a `neo4j.nodeValue` but attempting to cast this to `neo4j.Node` does not work.

```
// This returns an empty interface of type neo4j.nodeValue
nodeValue := reflect.Indirect(reflect.ValueOf(data["answer"])).Interface()

// This should work because neo4j.nodeValue implements the interface methods for neo4j.Node
node := nodeValue.(neo4j.Node)

// But it panics
panic: interface conversion: neo4j.nodeValue is not neo4j.Node: missing method Id
```

**Comment by ali-ince** [comment]
Hi @bmschwartz,

Just tried to reproduce the error you're experiencing with the following code, and everything works fine for me. Could you please provide some kind of reproduction steps, or even better code?

```golang
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/neo4j/neo4j-go-driver/neo4j"
)

var uri = "bolt://localhost:7687"
var username = "neo4j"
var password = "password"
var query = "CREATE (n1:User { userId: 'X' }), (n2:User { userId: 'Y' }) RETURN { u1: n1, u2: n2  }"

func run() error {
	var (
		driver  neo4j.Driver
		session neo4j.Session
		result  neo4j.Result
		err     error
	)

	useConsoleLogger := func() func(config *neo4j.Config) {
		return func(config *neo4j.Config) {
			config.Log = neo4j.ConsoleLogger(neo4j.ERROR)
		}
	}

	// Construct a new driver
	if driver, err = neo4j.NewDriver(uri, neo4j.BasicAuth(username, password, ""), useConsoleLogger()); err != nil {
		return err
	}
	defer driver.Close()

	// Acquire a session
	if session, err = driver.Session(neo4j.AccessModeRead); err != nil {
		return err
	}
	defer session.Close()

	// Execute the transaction function
	if result, err = session.Run(query, nil); err != nil {
		return err
	}

	for result.Next() {
		returnedMap := result.Record().GetByIndex(0).(map[string]interface{})
		node1 := returnedMap["u1"].(neo4j.Node)
		node2 := returnedMap["u2"].(neo4j.Node)

		fmt.Println(node1)
		fmt.Println(node2)
	}

	return result.Err()
}

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
		os.Exit(1)
	}

	os.Exit(0)
}
```


Thanks.

**Comment by bmschwartz** [comment]
I rewrote it along the lines of your code and it's working. Maybe initially I was doing something weird between getting `returnedMap` and then trying to access the data. All good now though. I'll close the issue.

Thanks for the help!
