### ISSUE TITLE
How to contribution Code

### ISSUE THREAD

**Issue by youngxhui** [neo4j/neo4j-go-driver#519]
Last month, I discovered that in a clustered environment, if the leader abruptly shuts down, the client does not immediately reconnect to the new leader machine. Instead, it needs to wait for a buffering period. To address this issue, I submitted a pull request (PR). However, the PR requires signing a Contributor License Agreement (CLA). I have already sent an email to the relevant address, [cla+noreply@neotechnology.com](mailto:cla+noreply@neotechnology.com), but haven't received any response. Could you please advise on the next steps?

pr: #515

**Comment by StephenCathcart** [comment]
Apologies for the delayed response. Although we received your email, no CLA agreement was attached. Please refer to the instructions in the 'How to Sign' section at https://neo4j.com/developer/cla/, which includes a link to the [Neo4j CLA](https://dist.neo4j.org/neo4j-cla.pdf). If needed, you can submit another CLA request. 

While I can't review your code until the CLA is signed, based on the PR description, I see that a fix for the 'force refresh routing table' issue has been recently implemented and will be resolved in an upcoming release.

**Comment by StephenCathcart** [comment]
@youngxhui I have received your updated CLA and have added you to our whitelist checklist.

**Comment by youngxhui** [comment]
> @youngxhui I have received your updated CLA and have added you to our whitelist checklist.

thx
