### ISSUE TITLE
Govendor is throwing error

### ISSUE THREAD

**Issue by mesameen** [neo4j/neo4j-go-driver#52]
$ govendor fetch github.com/neo4j/neo4j-go-driver                                                                                                                                                # cd E:\projects\go\.cache\govendor\github.com\neo4j\neo4j-go-driver; git reset --hard origin/master                                                                                             fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.                                                                                                     Use '--' to separate paths from revisions, like this:                                                                                                                                            'git  [...] -- [...]'                                                                                                                                                   Error: failed to sync to latest revision exit status 128                                                                                                                                         Failed to fetch package "github.com/neo4j/neo4j-go-driver"                                                                                                                                       github.com/kardianos/govendor/context.(*Context).Alter                                                                                                                                                   E:/projects/go/src/github.com/kardianos/govendor/context/modify.go:712                                                                                                                   github.com/kardianos/govendor/run.(*runner).Modify                                                                                                                                                       E:/projects/go/src/github.com/kardianos/govendor/run/modify.go:152                                                                                                                       github.com/kardianos/govendor/run.(*runner).run                                                                                                                                                          E:/projects/go/src/github.com/kardianos/govendor/run/run.go:98                                                                                                                           github.com/kardianos/govendor/run.Run                                                                                                                                                                    E:/projects/go/src/github.com/kardianos/govendor/run/run.go:44                                                                                                                           main.main                                                                                                                                                                                                E:/projects/go/src/github.com/kardianos/govendor/main.go:35                                                                                                                              runtime.main                                                                                                                                                                                             C:/Go/src/runtime/proc.go:201                                                                                                                                                            runtime.goexit                                                                                                                                                                                           C:/Go/src/runtime/asm_amd64.s:1333
--

**Comment by ali-ince** [comment]
I believe community has answered your question [here](https://community.neo4j.com/t/govendor-is-throwing-below-error/6383).
