### ISSUE TITLE
pkg-config: exec: "pkg-config": executable file not found in %PATH%

### ISSUE THREAD

**Issue by mesameen** [neo4j/neo4j-go-driver#53]
$ go run main.go                                                                                                                                                                                 # pkg-config --cflags  -- seabolt17                                                                                                                                                              pkg-config: exec: "pkg-config": executable file not found in %PATH%
--

**Comment by ali-ince** [comment]
Please follow instructions available at https://github.com/neo4j/neo4j-go-driver for different platforms including windows.
