### ISSUE TITLE
unable to acquire connection from connector: error: [13] an unknown TLS error, state: 4, context: _open(neo4j-drivers/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection

### ISSUE THREAD

**Issue by dw130** [neo4j/neo4j-go-driver#54]
hi:
	driver, err = neo4j.NewDriver(g.url, neo4j.BasicAuth(g.user, g.pass, ""))
    if err != nil {
    	log.Error("new graph driver fail:%v",err)
        return nil
    }

    session, err = driver.Session(neo4j.AccessModeWrite)
    if err != nil {
       	log.Error("new graph Session fail:%v",err)
        return nil
    }

the two steps below  does not get any errors, I can telnet the server correctly

but when goes 
_,err := g.session.Run( s,nil, neo4j.WithTxTimeout(5*time.Second) ); 
got error like this :
unable to acquire connection from connector: error: [13] an unknown TLS error, state: 4, context: _open(neo4j-drivers/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection

use the lastest version of seabolt
https://github.com/neo4j-drivers/seabolt/blob/1c0e8c26d84fa5c830c0be10b33206ff5ea43baa/src/seabolt/src/bolt/communication.c#L73

Please give some idea to debug this error, I do not get any way to investigate it,thanks
@ali-ince  I use the py2neo on the same machine and it does work

**Comment by ali-ince** [comment]
Hi,

Could you please enable debug level logging and provide the logs? It's probably something related with TLS.

Thanks.

**Comment by dw130** [comment]
@ali-ince  log from server:
```
2019-04-28 09:46:52.794+0000 WARN  badMessage: 400 Illegal character 0x16 for HttpChannelOverHttp@77eda9fd{r=0,c=false,a=IDLE,uri=}
2019-04-28 09:46:52.797+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@9ce7732[p=1,l=326,c=8192,r=325]={\x16<<<\x03\x01\x01A\x01\x00\x01=\x03\x03\xC6B-N\xFd\xBf\x0b...\x03\x02\x03\x03\x02\x01\x02\x02\x02\x03\x00\x0f\x00\x01\x01>>>wser/\r\nAccept-Enc...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2019-04-28 09:46:52.797+0000 WARN  badMessage: 400 Illegal character 0x16 for HttpChannelOverHttp@68f411b2{r=0,c=false,a=IDLE,uri=}
2019-04-28 09:46:52.800+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@1b887feb[p=1,l=326,c=8192,r=325]={\x16<<<\x03\x01\x01A\x01\x00\x01=\x03\x03v\x9f\x0ec\xE0B1...\x03\x02\x03\x03\x02\x01\x02\x02\x02\x03\x00\x0f\x00\x01\x01>>>wser/\r\nAccept-Enc...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
```

**Comment by ali-ince** [comment]
Hi @dw130,

We need the debug level logs for the driver itself, and you can have a look at https://github.com/neo4j/neo4j-go-driver#logging for how to configure driver logging.

Thanks.

**Comment by GuitooStephan** [comment]
I am facing the same issue after following the configuration snippet,

My error is 
"unable to acquire connection from connector: error: [1] an unknown error occurred, state: 4, context: plain_socket_open(/seabolt/src/seabolt/src/bolt/communication-plain.c:131), connect error code: 99"

**Comment by ali-ince** [comment]
Would you please provide more details on your environment, like your operating system and it's version, what version of neo4j server, etc?

And also it would be very useful if you could provide debug level logs, as described in https://github.com/neo4j/neo4j-go-driver#logging.

**Comment by GuitooStephan** [comment]
I am running my application and neo4j using docker compose 

My docker compose looks like this 

`version: '3.3'

services:
  neo4j:
    image: neo4j:3.5.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
    volumes:
      - ./neo4j/data:/data
    networks: 
      - neo4j_go_net
  api:
    image: golang:1.12-alpine
    build : .
    volumes :
      - ".:/go/src/app"
    ports:
      - "8080:8080"
    env_file: .env
    networks: 
      - neo4j_go_net
    links:
      - neo4j
      - memcached
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - neo4j
      - memcached
networks:
  neo4j_go_net:
    driver: bridge
volumes:
  dgraph:`

In my main.go, here is the command I am running in order to connect,
`driver, err = neo4j.NewDriver(neo4jURL, neo4j.NoAuth(), useConsoleLogger(neo4j.ERROR))
	if err != nil {
		log.Fatal("Error creating neo4j driver")
	}
	defer driver.Close()`

I have been trying to get some logs but all I have is about the server, nothing about the driver

**Comment by mvid** [comment]
Also having this issue, also running in alpine docker. My example is here:
https://github.com/mvid/neo4j-go-graphql-docker

**Comment by mvid** [comment]
Strangely enough, this seemed to be a manifestation of an incorrect username/password. It is working for me now

**Comment by youshy** [comment]
Got the same issue when running below:
```
	_, err := s.Run("MERGE (s:Page {url: $url, depth: $depth, status: $status}) return s", map[string]interface{}{
		"url":    n.Url,
		"depth":  n.Depth,
		"status": n.Status,
	})
	if err != nil {
		log.Fatalf("Unable to create link data: %v", err)
	}
```

My error:
```
Unable to create link data: unable to acquire connection from connector: error: [11] connection refused, state: 4, context: plain_socket_open(/seabolt/src/seabolt/src/bolt/communication-plain.c:151), select error code: 111
```

Running the container with `golang:alpine`

**Comment by davisford** [comment]
We are getting the same now running integration tests against neo4j-enterprise inside `docker-compose`

Our docker-compose file looks like:

```
version: "3.4"
services:
  neo4j:
    image: neo4j:3.5.9-enterprise
    environment:
      NEO4J_AUTH: "none"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - db-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
  neo4j-client:
    build: .
    image: neo4j-client:latest
    depends_on:
      - neo4j
    command:
      [
        "/wait-for.sh",
        "neo4j:7687",
        "--",
        "neo4j-client",
        "--insecure",
        "--verbose",
        "--non-interactive",
        "--no-known-hosts",
        "-i",
        "/migrations/create-indexes.cyp",
        "neo4j",
        "7687",
      ]
  authztest:
    build:
      context: ../
      target: test
    container_name: $CONTAINER_NAME
    image: authz:test
    volumes:
      - $BUILD_DIR:/tests
    environment:
      DB_CONTAINER_NAME: ${CONTAINER_NAME}
    depends_on:
      - neo4j
    command:
      ["./db/src/wait-for.sh", "neo4j:7687", "--", "./db/jenkins-run-tests.sh"]
volumes:
  db-data:
```

**Comment by davisford** [comment]
FWIW -- our Jenkins CI server had the Docker settings limited to `2GB` of RAM, and that appears to have been the death knell.  Up the RAM, and our tests started passing.  There are other caveats -- like you need to pass in a dynamic container name, and also periodically run a jenkins job that does `docker prune system`.  

![Screen Shot 2019-12-18 at 2 34 10 PM](https://user-images.githubusercontent.com/186677/71139834-625d6b80-21dd-11ea-9997-7ea37bef1c83.png)

**Comment by parvezshah** [comment]
facing the same issue 
"an unknown TLS error, state: 4, context: _open(/tmp/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection [recovered]"
Debug log 
GOROOT=/snap/go/4901 #gosetup
GOPATH=/home/parvezshah/go #gosetup
/snap/go/4901/bin/go test -c -o /tmp/___TestPageStore_CreatePageEmailStore_Save_in_gitlab_com_mytradewall_gospace_applications_wall_page_internal_app_stores_neo4j gitlab.com/mytradewall/gospace/applications/wall/page/internal/app/stores/neo4j #gosetup
/snap/go/4901/bin/go tool test2json -t /tmp/___TestPageStore_CreatePageEmailStore_Save_in_gitlab_com_mytradewall_gospace_applications_wall_page_internal_app_stores_neo4j -test.v -test.run ^TestPageStore_CreatePageEmailStore_Save$ #gosetup
=== RUN   TestPageStore_CreatePageEmailStore_Save
INFO   : 2020/01/19 14:17:20.365449 [connector]: Version 1.7.4 [ea1a58c]
INFO   : 2020/01/19 14:17:20.365523 [pool-1]: Creating pool towards localhost:8798
INFO   : 2020/01/19 14:17:20.365707 [pool-1]: Acquiring connection from the pool towards localhost:8798
INFO   : 2020/01/19 14:17:20.365715 [addr]: Resolving address localhost:8798
INFO   : 2020/01/19 14:17:20.365922 [addr]: Host resolved to 1 IP address
INFO   : 2020/01/19 14:17:20.365953 [conn-1]: Opening IPv4 connection to 127.0.0.1 at port 8798
INFO   : 2020/01/19 14:17:20.367968 [conn-1]: <DEFUNCT> [_open(/tmp/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection]
--- FAIL: TestPageStore_CreatePageEmailStore_Save (0.00s)
panic: unable to acquire connection from connector: error: [13] an unknown TLS error, state: 4, context: _open(/tmp/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection [recovered]
	panic: unable to acquire connection from connector: error: [13] an unknown TLS error, state: 4, context: _open(/tmp/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection


Client environment
go version go1.13.5 linux/amd64
 
Neo4j
https://github.com/bitnami/bitnami-docker-neo4j/blob/master/docker-compose.yml

Client code 
https://github.com/neo4j/neo4j-go-driver

**Comment by viveknarang** [comment]
@ali-ince I am facing a similar issue. Looking forward to your expert advice. Thanks in advance. 

```
INFO   : 2020/01/21 19:22:45.914789 [connector]: Version 1.7.4 [ea1a58c]
INFO   : 2020/01/21 19:22:45.914883 [pool-1]: Creating pool towards localhost:7687
INFO   : 2020/01/21 19:22:45.916784 [pool-1]: Acquiring connection from the pool towards localhost:7687
INFO   : 2020/01/21 19:22:45.916876 [addr]: Resolving address localhost:7687
INFO   : 2020/01/21 19:22:45.918273 [addr]: Host resolved to 1 IP address
INFO   : 2020/01/21 19:22:45.918418 [conn-1]: Opening IPv4 connection to 127.0.0.1 at port 7687
INFO   : 2020/01/21 19:22:45.921497 [conn-1]: <DEFUNCT> [_open(/tmp/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection]
INFO   : 2020/01/21 19:22:45.925466 [pool-1]: Destroying pool towards localhost:7687
INFO   : 2020/01/21 19:22:45.925525 [conn-1]: Closing connection
DEBUG  : 2020/01/21 19:22:45.925575 [conn-1]: Closing socket
INFO   : 2020/01/21 19:22:45.925771 [conn-1]: <DISCONNECTED>

```
Neo4j Version: 4.0.0
OS: Ubuntu 18.04.3 LTS

**Comment by rogaha** [comment]
Same error here:

```
api-go     | 16:35:30 app         | 2020/01/24 16:35:30 Starting server on port 8080 with neo4j bolt://neo4j:7687
api-go     | 16:35:38 app         | INFO   : 2020/01/24 16:35:38.410539 [connector]: Version 1.7.4-dev [875643c]
api-go     | INFO   : 2020/01/24 16:35:38.410604 [pool-1]: Creating pool towards neo4j:7687
api-go     | 16:35:38 app         | INFO   : 2020/01/24 16:35:38.411367 [pool-1]: Acquiring connection from the pool towards neo4j:7687
api-go     | INFO   : 2020/01/24 16:35:38.411434 [addr]: Resolving address neo4j:7687
api-go     | 16:35:38 app         | INFO   : 2020/01/24 16:35:38.414747 [addr]: Host resolved to 1 IP address
api-go     | INFO   : 2020/01/24 16:35:38.414956 [conn-1]: Opening IPv4 connection to 172.20.0.2 at port 7687
api-go     | 16:35:38 app         | INFO   : 2020/01/24 16:35:38.417676 [conn-1]: <DEFUNCT> [_open(/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection]
api-go     | 16:35:38 app         | INFO   : 2020/01/24 16:35:38.418086 [pool-1]: Destroying pool towards neo4j:7687
api-go     | INFO   : 2020/01/24 16:35:38.418126 [conn-1]: Closing connection
api-go     | DEBUG  : 2020/01/24 16:35:38.418177 [conn-1]: Closing socket
api-go     | 16:35:38 app         | INFO   : 2020/01/24 16:35:38.418366 [conn-1]: <DISCONNECTED>
api-go     | 16:35:38 app         | 2020/01/24 16:35:38 error querying search: unable to acquire connection from connector: error: [13] an unknown TLS error, state: 4, context: _open(/seabolt/src/seabolt/src/bolt/communication.c:74): unable to establish connection
```

**Comment by raynjamin** [comment]
I don't know if this helps any of you, since you're using timeouts that I am not, but I was receiving this error and solved it by disabling tls in the call to NewDriver like so:

```
var err error
	var driver neo4j.Driver
	if driver, err = neo4j.NewDriver("bolt://graph:7687", neo4j.BasicAuth("neo4j", "neo4j", ""), func(c *neo4j.Config) {
		c.Encrypted = false
	}); err != nil {
		fmt.Println("Error while establishing graph connection")
	}
```

**Comment by sahi1422** [comment]
same issue ;(

**Comment by domdavis** [comment]
Was also getting this issue when running Neo4j in Docker. Pulled on a few threads and got it working. tl;dr:

```
export BOLT_CERTS=/some/path
mkdir -p ${BOLT_CERTS}/bolt/trusted
mkdir -p ${BOLT_CERTS}/bolt/revoked
cd ${BOLT_CERTS}
openssl req -x509 -newkey rsa:4096 -keyout private.key \
  -out public.crt -days 36500 -subj '/CN=localhost' -nodes
chmod 400 private.key
docker run -d -p=7473:7473 -p=7474:7474 -p=7687:7687 \
  -v ${BOLT_CERTS}/bolt:/var/lib/neo4j/certificates/bolt \
  -e=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
  -e=NEO4J_dbms_connector_bolt_tls__level=REQUIRED \
  -e=NEO4J_dbms_ssl_policy_bolt_enabled=TRUE \
  --user="$(id -u):$(id -g)" \
  --name neo4j neo4j:enterprise
```

By default Neo4j doesn't configure TLS (https://neo4j.com/docs/operations-manual/current/security/ssl-framework/). Example 11.2 gives a snippet to get bolt working over TLS. We then need to mount the generated certs and the directory structure for Docker to see (`-v` option), tell Neo4j that tls is required (you can use `OPTIONAL` too) and enable the ssl policy. These are set using config overrides from the official image (https://neo4j.com/docs/operations-manual/current/docker/configuration/). Finally the permissions need to be correct so run Neo4j as the current user to save having to faff with UIDs matching.

**Comment by GabrielJiang-J** [comment]
> I don't know if this helps any of you, since you're using timeouts that I am not, but I was receiving this error and solved it by disabling tls in the call to NewDriver like so:
> 
> ```
> var err error
> 	var driver neo4j.Driver
> 	if driver, err = neo4j.NewDriver("bolt://graph:7687", neo4j.BasicAuth("neo4j", "neo4j", ""), func(c *neo4j.Config) {
> 		c.Encrypted = false
> 	}); err != nil {
> 		fmt.Println("Error while establishing graph connection")
> 	}
> ```

“c.Encrypted = false“ is very important, it solves the problem, thanks!

**Comment by karankumarshreds** [comment]
```Go
  // Neo4JConfig{
  //   username: "neo4j",
  //   password: "password",
  //   connstring: "neo4j://localhost:7687",
  // },

	driver, err2 := neo4j.NewDriver(
		neo4jConfig.connstring,
		neo4j.BasicAuth(neo4jConfig.username, neo4jConfig.password, ""),
		func(c *neo4j.Config){ 👈
			c.Encrypted = false
		},
	)
	checkForErrors(err2, "Cannot connect to NEO4J")
	defer driver.Close()
	session, err := driver.NewSession(neo4j.SessionConfig{})
	checkForErrors(err, "Unable to create a new session")
	_, err5 := session.Run(
		`
		 CREATE (p:Person {id: $id, name: $name}) RETURN p.id, p.name;
		 MATCH  (p:Person {id: $id, name: $name}) DELETE p;
		`,
		map[string]interface{}{
			"id": 1,
			"name": "John Doe",
		},
	)
	checkForErrors(err5, "Unable to run a query")
	log.Println("Successfully connected with Neo4j 🎉")
```
