### ISSUE TITLE
Session is still usable even after explicitly closing it

### ISSUE THREAD

**Issue by oleriajm** [neo4j/neo4j-go-driver#569]
## Guidelines

https://github.com/neo4j/neo4j-go-driver/pull/568

The Session must not be usable after the caller closed it explicitly.

Following pattern works just fine at the moment

	session := driver.NewSession(ctx, sessionConfig)
        session.Close()

        session.ExecuteRead(...)
        // and keep using session with more operations...
This is because Closing session cleans up pool/router etc, but all the references are still preserved.

As a good practice, the behavior should be fail-fast/fail-hard once you called Close on it

- Neo4j version: 5.0.0
- Operating system: n/a
- API/Driver: go
- **Steps to reproduce**

see here https://github.com/neo4j/neo4j-go-driver/pull/568

### Steps to reproduce

see https://github.com/neo4j/neo4j-go-driver/pull/568

**Comment by StephenCathcart** [comment]
@oleriajm thank you very much for bringing this to our attention. I'm able to reproduce the bug on my end. I'll review the attached PR asap.

**Comment by StephenCathcart** [comment]
Fixed by PR https://github.com/neo4j/neo4j-go-driver/pull/570, attempting to use a closed session now returns a usage error. Thank you @oleriajm for bringing this to our attention 👍.
