### ISSUE TITLE
Binary release installation instructions

### ISSUE THREAD

**Issue by pzurek** [neo4j/neo4j-go-driver#60]
I feel like this issue belongs more in the [seabolt](https://github.com/neo4j-drivers/seabolt) repo but **Issues** are not enabled there.
So, it would be nice to have some more detailed installation instructions for the binary releases on all supported platforms.

**Comment by technige** [comment]
Could you let us know which platform you need instructions for?

**Comment by pzurek** [comment]
macOS would be the key for me at the moment.

**Comment by daylerees** [comment]
I've extracted the content into `/usr` but now I'm getting:

`github.com/neo4j-drivers/gobolt@v1.7.4/config.go:25:10: fatal error: 'bolt/bolt.h' file not found`

**Comment by ali-ince** [comment]
Hi all,

Please find more details about how to install binary packages [here](https://github.com/neo4j-drivers/seabolt#installing-from-packages).

Thanks.
