### ISSUE TITLE
cannot find -lseabolt17

### ISSUE THREAD

**Issue by 599020328** [neo4j/neo4j-go-driver#62]
i have installed seabolt, and i don't know whether it success.
![image](https://user-images.githubusercontent.com/23151116/60106255-74fb6880-9797-11e9-9cd5-946d991e35a0.png)
but when i use go get github.com/neo4j/neo4j-go-driver/neo4j
it return error : x86_64-w64-mingw32/bin/ld.exe: cannot find -lseabolt17
collect2.exe: error: ld returned 1 exit status
is anyone know how should i do to solve it, i have tryed a long time, but it also have this error. thanks for help！

**Comment by ololosha228** [comment]
same issue:
```
# pkg-config --cflags seabolt17
Package seabolt17 was not found in the pkg-config search path.
Perhaps you should add the directory containing `seabolt17.pc'
to the PKG_CONFIG_PATH environment variable
No package 'seabolt17' found
pkg-config: exit status 1
```

**Comment by ali-ince** [comment]
Did you follow the steps described at https://github.com/neo4j/neo4j-go-driver#source? Please ensure that you've set `PKG_CONFIG_PATH` environment variable to `F:/goworkspace/src/github.com/neo4j-drivers/seabolt/build-mingw-release/dist` and also verify that you've the correct `pkg-config` installed on your system as pointed out https://github.com/neo4j/neo4j-go-driver#pkg-config.

**Comment by 599020328** [comment]
yes, i have followed all the step, if the PKG_CONFIG_PATH and pkg-config not correct,  will have another error. but i don't know why the error i have, and i also can't find the answer in google, so i'm here ask for help.
my error shot : 
![image](https://user-images.githubusercontent.com/23151116/60244738-9ff7d080-98ed-11e9-9680-f642ed99a801.png)

**Comment by 599020328** [comment]
i solve it now, thank you very much. i test the ld command use --verbose, and i find the fir  the ld shell  scan was the mingw64/usr/lib, and the file is libseabolt17.a, so i copy the 2 file under /seabolt/lib to  mingw64/usr/lib and it success.
thank you for your help.
