### ISSUE TITLE
exit status 3221225781

### ISSUE THREAD

**Issue by jiurenm** [neo4j/neo4j-go-driver#65]
go run main.go
exit status 3221225781

**Comment by ynnynn** [comment]
same issue

once i import the package and call neo4j.NewDriver(), the program exist with status 3221225781

**Comment by ali-ince** [comment]
Hi,

Given the lack of information provided, the only possibility I can think of is, you don't have the required seabolt DLLs in path. Those are;

- If you're using MINGW compiled binary distribution (https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-win64-mingw.zip);
   - libseabolt17.dll
- If you're using MSVC compiled binary distribution (https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-win64-msvc.zip);
   - seabolt17.dll
   - vcruntime140.dll
   - msvcp140.dll
   - concrt140.dll

Those DLL's can be found in the downloaded binary zip files under its `bin` folder.

Please verify if this resolves you issues or provide with more detailed, clear reproducible steps for us  to reproduce and work on the error.
