### ISSUE TITLE
[Feature Request] please add godoc

### ISSUE THREAD

**Issue by davisford** [neo4j/neo4j-go-driver#67]
## Guidelines

> If you want to make a feature request, please prefix your issue title with `[Feature Request]` so that it is clear to us. 

It would be of great value if you could add godoc with comments.  Not being critical -- but it is fairly standard for golang libs, and tougher for devs to navigate around the source + tests to figure out what/how to do certain things (transactions, for example).

**Comment by BlackMocca** [comment]
I found godoc [here](https://godoc.org/github.com/neo4j/neo4j-go-driver/neo4j)

**Comment by davisford** [comment]
Sweet -- can we link that off the main `README.md` ?

https://godoc.org/github.com/neo4j/neo4j-go-driver/neo4j

**Comment by 2hdddg** [comment]
I will add this to the 1.8 branch
