### ISSUE TITLE
hi, why return nil here. This cause whether session is closed or not is confused.

### ISSUE THREAD

**Issue by Zddup** [neo4j/neo4j-go-driver#69]
https://github.com/neo4j/neo4j-go-driver/blob/934739616886b903306e1df80aa58047407a1971/neo4j/session_impl.go#L67

**Comment by 2hdddg** [comment]
Hi @Zddup it sure looks like a bug, the 1.7 driver is currently rewritten so this code will not look the same at all. Should be fixed in 1.8 version.
