### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by LeMoussel** [neo4j/neo4j-go-driver#73]
Hi,

I'm new to Neo4j and I've been playing around with the whole platform. Lately, I've been experimenting with interacting with the DB from a Go program.
To do this, I rewrote this GO code [goneo-example](https://github.com/paulosuzart/goneo-example/blob/master/main.go) using `neo4j-go-driver`. 

For the `merge` function, I did this 

```
func merge(absoluteURL string, depth int, neo4jDriver neo4j.Driver) error {
	var (
		neo4jSession neo4j.Session
		err          error
	)

	if neo4jSession, err = neo4jDriver.Session(neo4j.AccessModeWrite); err != nil {
		return err
	}
	defer neo4jSession.Close()

	_, err = neo4jSession.Run("MERGE (p: page {url: $url, depth: $depth}) RETURN p", map[string]interface{}{
		"url":   absoluteURL,
		"depth": depth,
	})

	//_, err = neo4jSession.Run("CREATE ()", nil)) // Also poor perfomance

	return err
}
```
But I'm getting weaker performance (also with `CREATE ()`).
I did this because in the documentation it says: 

> The driver is thread-safe, while the session or the transaction is not thread-safe.

I don't understand why I have poor performance since it is  considerably cheap to create new sessions and transactions.

**Comment by 2hdddg** [comment]
Hi @LeMoussel 
How do you measure performance in this case? When session is created the first time it will setup a new connection to the server which will be reused among sessions. So you would need to run the merge function multiple times or create an initial session that you close before measuring the merge function.

**Comment by 2hdddg** [comment]
Please rerun your tests against the 1.8 branch and open a new issue if there still is an issue.
