### ISSUE TITLE
Naming should adhere to Go conventions

### ISSUE THREAD

**Issue by joe-mann** [neo4j/neo4j-go-driver#78]
As per the "Initialisms" section in the [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#initialisms), initialisms such as "ID" (short for "identifier") should written as either "id" or "ID" - and not "Id".

There are several examples of deviations from this convention in the neo4j module. Aside from being an unnecessary departure from these naming conventions, golint (which is enabled by default when using the Go extension in VS Code) raises messages when you need to mock certain interfaces (such as Node or Relationship) for testing purposes.

As an aside, there are various other "style mistakes" raised by golint in the project. But unlike the misspelling of "ID" in exported interfaces, none of these are likely to "leak" into other packages that import it.

Fixing this issue obviously constitutes a breaking change to the API, which is why I think it should be strongly considered v2.0 (which I see has a dev branch).

**Comment by 2hdddg** [comment]
@joe-mann next breaking changing version will be a v4.0 (versioning scheme changed to relate to server version). Work for that one is planned but not started, we will then consider style guides.
