### ISSUE TITLE
[Feature Request] Multi-tenant connections.

### ISSUE THREAD

**Issue by grizzly-monkey** [neo4j/neo4j-go-driver#94]
- Neo4j version: Enterprise 4.0.3
- Neo4j Mode: Single instance
- Operating system: (Ubuntu 16.10 on AWS)

It would be great to have a support for multitenant db connections.
So as to switch db for each tenant on the fly to do the graph operations.

**Comment by technige** [comment]
Thank you for your message @grizzly-monkey. This is already on our roadmap for later this year.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Go Driver 4.0](https://trello.com/c/txhv49c2/8-go-driver-40)

**Comment by grizzly-monkey** [comment]
@technige  just wanted to know any tentative dates for this ? we want plan dev accordingly. even alpha / beta is fine for us to start the dev.

**Comment by 2hdddg** [comment]
@grizzly-monkey we will try to include this in the upcoming 1.18 release. Originally we planned to just get rid of cgo dependency in that release but since mutl-tenant/multidatabase support is a popular feature ...

**Comment by 2hdddg** [comment]
Feature included in v1.8.0-beta03
